
const actionTypes:any = {
  LOAD_POSTS : "LOAD_POSTS",
  SHOW_POST_DETAILS : "SHOW_POST_DETAILS",
  ADD_POST : "ADD_POST",
  DELETE_POST : "DELETE_POST",
  EDIT_POST : 'EDIT_POST',
  SHOW_ERROR : "SHOW_ERROR",
  ADD_DUMMY_POST : "ADD_DUMMY_POST",
  DELETE_DUMMY_POST : "DELETE_DUMMY_POST",
  SHOW_DETAILS_DUMMY_POST : "SHOW_DETAILS_DUMMY_POST",
  EDIT_DUMMY_POST : "EDIT_DUMMY_POST"
}
export default actionTypes