const actionTypes:any = {
  RECEIVE_TRANSLATED_TEXT : "RECEIVE_TRANSLATED_TEXT",
  SHOW_ERROR : "SHOW_ERROR",
  BEGIN_TRANSLATION : "BEGIN_TRANSLATION",
  ADD_BOOKMARK : "ADD_BOOKMARK",
  DELETE_BOOKMARK : "DELETE_BOOKMARK"
}
export default actionTypes